import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import test from 'node:test';
import YAML from 'yaml';

const root = new URL('../', import.meta.url);
const read = (file) => fs.readFileSync(new URL(file, root), 'utf8');
const exists = (file) => fs.existsSync(new URL(file, root));

test('call scenarios are authored in YAML and generated for runtime', () => {
  assert.ok(exists('schemas/call-scenario.schema.json'));
  assert.ok(exists('scenarios/audio.yml'));

  const audio = YAML.parse(read('scenarios/audio.yml'));
  assert.equal(audio.id, 'audio');
  assert.equal(audio.catalog_order, 10);
  assert.equal(audio.scenario_intent, 'audio_issue');
  assert.equal(audio.workflow.issue_type, 'technical_support');
  assert.deepEqual(audio.frontend_actions.map((action) => action.id), ['show-audio', 'run-checks']);

  const generated = read('site/generated/scenarios.js');
  assert.match(generated, /Generated by scripts\/build-scenarios\.mjs/);
  assert.match(generated, /catalogOrder/);
  assert.match(generated, /scenario_intent/);
  assert.match(read('site/scenarios.js'), /from '\.\/generated\/scenarios\.js'/);
});

test('scenario generator verifies committed output is current', () => {
  execFileSync(process.execPath, ['scripts/build-scenarios.mjs', '--check'], {
    cwd: new URL('../', import.meta.url),
    stdio: 'pipe',
  });
});
